### PR TITLE
Adding cp4d folders

### PR DESCRIPTION
**Pull request by michelle-miller**

### CODE REVIEW

**Comment by germanattanasio** [comment]
@michelle-miller I think we need to add `.DS_Store` to the `.gitignore` files and then remove the two files from your PR.

**Comment by michelle-miller** [comment]
so, i moved the files out of the new folders,but i don't know how to add .DS_Store...

**Comment by cclauss** [comment]
Create a new file at the root of this repo named `.gitignore` and paste in the contents of https://github.com/github/gitignore/blob/master/Python.gitignore and add a new line to that file that contains `.DS_Store`.  The purpose of these files are explained at 
https://github.com/github/gitignore#a-collection-of-gitignore-templates

**Comment by michelle-miller** [comment]
@germanattanasio please make sure my changes are right before merging this - or pls let me knwo what to fix!

**Review by germanattanasio — APPROVED** [review]

**Pull request merged**
